engines:
  rubocop:
    enabled: false
  eslint:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- "__tests__/"
- ".eslintrc"
- "android/"
- "ios/"
- "example/"
