language: node_js
node_js:
  - "5"

install:
  - cd example
  - npm install https://github.com/markuswind/react-native-select-input-ios/tarball/master
  - cd ../
  - sh .update-example-module.sh
  - npm install
  - npm test

script:
  - npm test

branches:
  only:
    - master
